import { AlumniProfile } from "./alumni-store"

export const demoAlumni: AlumniProfile[] = [
  {
    id: 1,
    firstName: "Maria",
    lastName: "Rodriguez",
    email: "maria.rodriguez@email.com",
    phone: "+1-555-0123",
    address: {
      street: "123 Theatre St",
      city: "San Francisco",
      state: "CA",
      zipCode: "94102",
      country: "USA",
      latitude: 37.7749,
      longitude: -122.4194,
    },
    programsAttended: [
      {
        program: "MFA in Ensemble Based Physical Theatre",
        cohort: "2018-2020",
        graduationYear: 2020,
      },
    ],
    biography:
      "Maria is a passionate physical theatre artist who combines traditional commedia dell'arte with contemporary social issues. She founded Teatro Nuevo in San Francisco, focusing on bilingual performances that bridge cultural divides.",
    currentWork: {
      title: "Artistic Director",
      organization: "Teatro Nuevo",
      location: "San Francisco, CA",
    },
    tags: ["directing", "commedia dell'arte", "bilingual theatre"],
    languagesSpoken: ["English", "Spanish"],
    professionalAchievements: ["Founded Teatro Nuevo (2021)", "SF Arts Commission Grant Recipient (2022)"],
    portfolioLinks: {
      website: "teatronuevo.org",
      instagram: "@teatronuevo",
    },
    experiencesAtDellArte: ["Commedia Intensive", "Mask Making Workshop"],
    referrals: [],
    lastUpdated: "2024-01-15",
    profilePrivacy: "public",
    donationHistory: [],
  },
  {
    id: 2,
    firstName: "James",
    lastName: "Chen",
    email: "james.chen@email.com",
    phone: "+1-555-0124",
    address: {
      street: "456 Performance Ave",
      city: "Portland",
      state: "OR",
      zipCode: "97201",
      country: "USA",
      latitude: 45.5152,
      longitude: -122.6784,
    },
    programsAttended: [
      {
        program: "Professional Training Program",
        cohort: "2019",
        graduationYear: 2019,
      },
    ],
    biography:
      "James specializes in mask work and has developed innovative techniques for integrating technology with traditional mask performance. He teaches workshops internationally and has performed with major theatre companies.",
    currentWork: {
      title: "Mask Artist & Educator",
      organization: "Pacific Theatre Collective",
      location: "Portland, OR",
    },
    tags: ["mask making", "technology integration", "teaching"],
    languagesSpoken: ["English", "Mandarin"],
    professionalAchievements: ["TEDx Speaker on Digital Masks (2023)", "Oregon Arts Fellowship (2022)"],
    portfolioLinks: {
      website: "jameschen-masks.com",
      linkedin: "james-chen-theatre",
    },
    experiencesAtDellArte: ["Advanced Mask Techniques", "Teaching Methodology"],
    referrals: [],
    lastUpdated: "2024-01-10",
    profilePrivacy: "public",
    donationHistory: [],
  },
  {
    id: 3,
    firstName: "Sarah",
    lastName: "Thompson",
    email: "sarah.thompson@email.com",
    phone: "+1-555-0125",
    address: {
      street: "789 Clown Blvd",
      city: "Austin",
      state: "TX",
      zipCode: "78701",
      country: "USA",
      latitude: 30.2672,
      longitude: -97.7431,
    },
    programsAttended: [
      {
        program: "Summer Workshop - Clown Intensive",
        cohort: "2020",
        graduationYear: 2020,
      },
    ],
    biography:
      "Sarah brings healing through laughter as a healthcare clown. She works in children's hospitals and elder care facilities, using Dell'Arte techniques to bring joy and comfort to patients and families.",
    currentWork: {
      title: "Healthcare Clown",
      organization: "Healing Hearts Hospital",
      location: "Austin, TX",
    },
    tags: ["clown", "healthcare clowning", "therapeutic arts"],
    languagesSpoken: ["English"],
    professionalAchievements: ["Certified Healthcare Clown (2021)", "Community Service Award (2023)"],
    portfolioLinks: {
      instagram: "@sarahtheclown",
      youtube: "SarahThompsonClown",
    },
    experiencesAtDellArte: ["Clown Intensive", "Medical Clowning Workshop"],
    referrals: [],
    lastUpdated: "2024-01-08",
    profilePrivacy: "public",
    donationHistory: [],
  },
  {
    id: 4,
    firstName: "Alessandro",
    lastName: "Bianchi",
    email: "alessandro.bianchi@email.com",
    phone: "+39-123-456-789",
    address: {
      street: "Via del Teatro 15",
      city: "Florence",
      state: "",
      zipCode: "50122",
      country: "Italy",
      latitude: 43.7696,
      longitude: 11.2558,
    },
    programsAttended: [
      {
        program: "International Summer School",
        cohort: "2021",
        graduationYear: 2021,
      },
    ],
    biography:
      "Alessandro is preserving and innovating traditional Italian theatre forms. He leads workshops across Europe and collaborates with Dell'Arte on international exchange programs.",
    currentWork: {
      title: "Theatre Director",
      organization: "Compagnia del Sole",
      location: "Florence, Italy",
    },
    tags: ["commedia dell'arte", "international collaboration", "cultural preservation"],
    languagesSpoken: ["Italian", "English", "French"],
    professionalAchievements: ["European Theatre Award (2022)", "Cultural Ambassador for Italy-US Arts Exchange"],
    portfolioLinks: {
      website: "compagniadelsole.it",
      linkedin: "alessandro-bianchi-theatre",
    },
    experiencesAtDellArte: ["International Summer School", "Cultural Exchange Program"],
    referrals: [],
    lastUpdated: "2024-01-12",
    profilePrivacy: "public",
    donationHistory: [],
  },
  {
    id: 5,
    firstName: "Aiyana",
    lastName: "Crow Feather",
    email: "aiyana.crowfeather@email.com",
    phone: "+1-555-0126",
    address: {
      street: "321 Sacred Way",
      city: "Santa Fe",
      state: "NM",
      zipCode: "87501",
      country: "USA",
      latitude: 35.687,
      longitude: -105.9378,
    },
    programsAttended: [
      {
        program: "MFA in Ensemble Based Physical Theatre",
        cohort: "2017-2019",
        graduationYear: 2019,
      },
    ],
    biography:
      "Aiyana weaves indigenous storytelling traditions with contemporary physical theatre. She creates powerful performances that honor her heritage while addressing modern social issues.",
    currentWork: {
      title: "Storyteller & Theatre Artist",
      organization: "Indigenous Arts Collective",
      location: "Santa Fe, NM",
    },
    tags: ["indigenous theatre", "storytelling", "cultural preservation"],
    languagesSpoken: ["English", "Lakota"],
    professionalAchievements: ["National Indigenous Arts Award (2023)", "Sundance Theatre Lab Fellow (2022)"],
    portfolioLinks: {
      website: "aiyanacrowfeather.com",
      instagram: "@aiyana_stories",
    },
    experiencesAtDellArte: ["MFA Program", "Indigenous Theatre Workshop"],
    referrals: [],
    lastUpdated: "2024-01-14",
    profilePrivacy: "public",
    donationHistory: [],
  },
] 